version: '2'

services:
  severnata-zvezda:
    image: gonz/quanterall-web-development:lts-16.31
    ports:
      - 3000:3000
    volumes:
      - ..:/workspace:cached
      - ./build/stack-work:/workspace/.stack-work:cached
      - ./build/root-stack:/root/.stack:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - YESOD_PGUSER=postgres
      - YESOD_PGPASS=postgres
      - YESOD_PGHOST=postgres
      - YESOD_PGPORT=5432
    depends_on:
      - postgres

  postgres:
    build:
      dockerfile: ./Dockerfile.postgres
      context: ..
    ports:
      - 5432:5432
    environment:
      - DEBUG=1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  default:
    driver: bridge